"""Finalize Upload Utility models and fix dependencies

Revision ID: 13477df6ba31
Revises: 
Create Date: 2025-09-27 14:54:39.062289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13477df6ba31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in an order that respects foreign key constraints.
    op.drop_table('user_roles')
    op.drop_table('role_access_policies')
    op.drop_table('scheduler_jobs')
    op.drop_table('dashboard_components')
    op.drop_table('data_mart')
    op.drop_table('dashboard')
    op.drop_table('roles')
    op.drop_table('access_policies')
    op.drop_table('theme')
    op.drop_table('data_source')
    op.drop_table('user')
    with op.batch_alter_table('dashboard_analytics', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('processing_completed_at')

    with op.batch_alter_table('upload_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'data_sources', ['data_source_id'], ['id'])
        batch_op.drop_column('destination_config')
        batch_op.drop_column('destination_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('destination_config', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_source_id')

    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('processed_at')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('dashboard_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('access_policies',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('filter_condition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='access_policies_pkey'),
    sa.UniqueConstraint('name', name='access_policies_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('theme',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('theme_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('styles', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='theme_pkey'),
    sa.UniqueConstraint('name', name='theme_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('data_mart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('data_mart_data_source_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('data_mart_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_mart_pkey'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('granted_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('user_roles_granted_by_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey'))
    )
    op.create_table('dashboard',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('theme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('layout', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], name=op.f('dashboard_theme_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('dashboard_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_pkey'))
    )
    op.create_table('data_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connection_details', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('data_source_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_source_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('must_reset_password', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dashboard_components',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('chart_library_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('position_x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position_y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('query_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chart_library_id'], ['chart_library.id'], name=op.f('dashboard_components_chart_library_id_fkey')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('dashboard_components_dashboard_id_fkey')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('dashboard_components_data_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_components_pkey'))
    )
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('schedule_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('scheduler_jobs_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduler_jobs_pkey'))
    )
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_system_role', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('role_access_policies',
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['access_policies.id'], name=op.f('role_access_policies_policy_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_access_policies_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'policy_id', name=op.f('role_access_policies_pkey'))
    )
    # ### end Alembic commands ###
