"""Initial migration with users and data_sources tables

Revision ID: f678e3078b24
Revises: 
Create Date: 2025-09-27 23:54:27.768475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f678e3078b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('connection_params', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('test_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_tested_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('test_query', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('connection_config', sa.TEXT(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('connection_params')

    op.create_table('data_source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('host', sa.VARCHAR(length=100), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('database', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('layout_config', sa.TEXT(), nullable=False),
    sa.Column('theme_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('filters_config', sa.TEXT(), nullable=True),
    sa.Column('mobile_layout', sa.TEXT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('last_viewed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('records_processed', sa.INTEGER(), nullable=True),
    sa.Column('records_success', sa.INTEGER(), nullable=True),
    sa.Column('records_failed', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('error_log', sa.TEXT(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['upload_templates.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_access_policies',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('policy_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['access_policies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'policy_id')
    )
    op.create_table('theme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('styles', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chart_library',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('chart_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('config_schema', sa.TEXT(), nullable=False),
    sa.Column('component_code', sa.TEXT(), nullable=False),
    sa.Column('css_styles', sa.TEXT(), nullable=True),
    sa.Column('preview_image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_components',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dashboard_id', sa.INTEGER(), nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('chart_library_id', sa.INTEGER(), nullable=True),
    sa.Column('position_x', sa.INTEGER(), nullable=False),
    sa.Column('position_y', sa.INTEGER(), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('config', sa.TEXT(), nullable=False),
    sa.Column('data_source_id', sa.INTEGER(), nullable=True),
    sa.Column('query_config', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['chart_library_id'], ['chart_library.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('theme_id', sa.INTEGER(), nullable=True),
    sa.Column('layout', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_marts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('data_source_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_templates',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('file_format', sa.VARCHAR(length=50), nullable=False),
    sa.Column('validation_rules', sa.TEXT(), nullable=True),
    sa.Column('transformation_rules', sa.TEXT(), nullable=True),
    sa.Column('data_source_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('upload_mode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('access_policies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('filter_condition', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dashboard_analytics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_library',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('css_variables', sa.TEXT(), nullable=False),
    sa.Column('component_styles', sa.TEXT(), nullable=True),
    sa.Column('color_palette', sa.TEXT(), nullable=False),
    sa.Column('typography', sa.TEXT(), nullable=True),
    sa.Column('preview_image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('permissions', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('schedule_expression', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('target_resource_id', sa.INTEGER(), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('next_run_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('granted_by', sa.INTEGER(), nullable=False),
    sa.Column('granted_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_mart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('data_source_id', sa.INTEGER(), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
