import React, { useState } from 'react';
import { RefreshCw, TrendingUp, TrendingDown, AlertTriangle, Lightbulb, Target, ChevronDown, ChevronUp } from 'lucide-react';

interface Trend {
  type: 'upward' | 'downward';
  metric: string;
  change: string;
  description: string;
  confidence: number;
}

interface Anomaly {
  index?: number;
  metric: string;
  expected: number;
  actual: number;
  severity: 'high' | 'medium' | 'low';
  description: string;
}

interface Recommendation {
  priority: 'high' | 'medium' | 'low';
  action: string;
  reason: string;
  impact: string;
}

interface AIInsightsData {
  keyFindings: string[];
  trends: Trend[];
  anomalies: Anomaly[];
  recommendations: Recommendation[];
  summary: string;
}

interface AIInsightsChartProps {
  data: AIInsightsData;
  metadata?: {
    analyzedCharts?: number;
    analyzedKPIs?: number;
    analyzedTimeSeries?: number;
    generatedBy?: string;
    timestamp?: string;
  };
  loading?: boolean;
  onRefresh?: () => void;
}

const AIInsightsChart: React.FC<AIInsightsChartProps> = ({ 
  data, 
  metadata,
  loading = false,
  onRefresh 
}) => {
  // ✨ EXPAND ALL SECTIONS BY DEFAULT for better visibility
  const [expandedSection, setExpandedSection] = useState<string | null>('all');

  const toggleSection = (section: string) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'bg-red-100 text-red-800 border-red-300';
      case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      case 'low': return 'bg-blue-100 text-blue-800 border-blue-300';
      default: return 'bg-gray-100 text-gray-800 border-gray-300';
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'high': return 'bg-red-50 border-red-300 text-red-900';
      case 'medium': return 'bg-orange-50 border-orange-300 text-orange-900';
      case 'low': return 'bg-yellow-50 border-yellow-300 text-yellow-900';
      default: return 'bg-gray-50 border-gray-300 text-gray-900';
    }
  };

  if (loading) {
    return (
      <div className="bg-gradient-to-br from-purple-50 via-indigo-50 to-pink-50 rounded-xl p-8 border-2 border-purple-200 min-h-[400px] flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-purple-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-lg font-semibold text-purple-900">🤖 AI is analyzing your data...</p>
          <p className="text-sm text-purple-700 mt-2">This may take a few moments</p>
        </div>
      </div>
    );
  }

  // Handle missing or invalid data
  if (!data || typeof data !== 'object') {
    return (
      <div className="bg-gradient-to-br from-red-50 via-orange-50 to-yellow-50 rounded-xl p-8 border-2 border-red-200 min-h-[400px] flex items-center justify-center">
        <div className="text-center">
          <span className="text-6xl mb-4 block">⚠️</span>
          <p className="text-lg font-semibold text-red-900">No Insights Available</p>
          <p className="text-sm text-red-700 mt-2">Unable to generate AI insights from the provided data.</p>
          {onRefresh && (
            <button
              onClick={onRefresh}
              className="mt-4 px-6 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          )}
        </div>
      </div>
    );
  }

  // Provide default empty arrays if properties are missing
  const safeData = {
    keyFindings: data.keyFindings || [],
    trends: data.trends || [],
    anomalies: data.anomalies || [],
    recommendations: data.recommendations || [],
    summary: data.summary || 'No summary available.'
  };

  return (
    <div className="bg-gradient-to-br from-purple-50 via-indigo-50 to-pink-50 rounded-xl p-6 border-2 border-purple-200 shadow-lg">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-2xl font-bold flex items-center gap-3">
            <span className="text-4xl">🤖</span>
            <span className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
              AI Insights & Recommendations
            </span>
          </h3>
          {metadata && (
            <p className="text-sm text-gray-600 mt-1 ml-16">
              Analyzed {metadata.analyzedCharts || 0} charts • Generated by {metadata.generatedBy || 'AI'}
              {metadata.timestamp && ` • ${new Date(metadata.timestamp).toLocaleTimeString()}`}
            </p>
          )}
        </div>
        {onRefresh && (
          <button
            onClick={onRefresh}
            className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors shadow-md hover:shadow-lg"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        )}
      </div>

      {/* Key Findings - Enhanced with Visual Breakdown */}
      <div className="mb-4">
        <button
          onClick={() => toggleSection('findings')}
          className="w-full flex items-center justify-between p-4 bg-gradient-to-r from-blue-50 to-cyan-50 rounded-lg border-2 border-blue-200 hover:border-blue-300 transition-colors"
        >
          <div className="flex items-center gap-3">
            <Lightbulb className="w-6 h-6 text-blue-600" />
            <span className="text-lg font-bold text-blue-900">💡 Key Findings & Performance Breakdown</span>
            <span className="px-2 py-1 bg-blue-200 text-blue-800 text-xs font-semibold rounded-full">
              {safeData.keyFindings.length}
            </span>
          </div>
          {expandedSection === 'findings' ? (
            <ChevronUp className="w-5 h-5 text-blue-600" />
          ) : (
            <ChevronDown className="w-5 h-5 text-blue-600" />
          )}
        </button>
          {(expandedSection === 'findings' || expandedSection === 'all') && (
          <div className="mt-2 p-4 bg-white rounded-lg border-2 border-blue-100">
            {/* ✨ EXACTLY 3 columns per row - clean structured layout */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
              {safeData.keyFindings.map((finding, index) => {
                // Detect insight type
                const isTopPerformer = finding.includes('🏆') || finding.includes('📍');
                const isTop3 = finding.includes('Top 3') || finding.includes('✅');
                const isBottom3 = finding.includes('Bottom 3') || finding.includes('⚠️');
                const isTrend = finding.includes('📈') || finding.includes('Trend');
                const hasPercentage = finding.match(/(\d+\.\d+)%/);
                
                // Determine color scheme
                let bgColor = 'from-blue-50 to-cyan-50';
                let borderColor = 'border-blue-200';
                let textColor = 'text-blue-600';
                
                if (isTop3 || isTopPerformer) {
                  bgColor = 'from-green-50 to-emerald-50';
                  borderColor = 'border-green-200';
                  textColor = 'text-green-600';
                } else if (isBottom3) {
                  bgColor = 'from-orange-50 to-red-50';
                  borderColor = 'border-orange-200';
                  textColor = 'text-orange-600';
                } else if (isTrend) {
                  bgColor = 'from-purple-50 to-indigo-50';
                  borderColor = 'border-purple-200';
                  textColor = 'text-purple-600';
                }
                
                return (
                  <div 
                    key={index} 
                    className={`p-3 rounded-lg border-2 ${borderColor} bg-gradient-to-br ${bgColor} hover:shadow-md transition-shadow`}
                  >
                    <p className="text-sm font-medium text-gray-800 leading-relaxed">
                      {finding}
                    </p>
                    {hasPercentage && (
                      <div className="mt-2 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                        <div 
                          className={`h-full ${textColor === 'text-green-600' ? 'bg-green-500' : textColor === 'text-orange-600' ? 'bg-orange-500' : 'bg-blue-500'} rounded-full transition-all duration-500`}
                          style={{ width: `${Math.min(parseFloat(hasPercentage[1]), 100)}%` }}
                        ></div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Trends */}
      {safeData.trends.length > 0 && (
        <div className="mb-4">
          <button
            onClick={() => toggleSection('trends')}
            className="w-full flex items-center justify-between p-4 bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg border-2 border-green-200 hover:border-green-300 transition-colors"
          >
            <div className="flex items-center gap-3">
              <TrendingUp className="w-6 h-6 text-green-600" />
              <span className="text-lg font-bold text-green-900">📈 Trends Detected</span>
              <span className="px-2 py-1 bg-green-200 text-green-800 text-xs font-semibold rounded-full">
                {safeData.trends.length}
              </span>
            </div>
            {expandedSection === 'trends' ? (
              <ChevronUp className="w-5 h-5 text-green-600" />
            ) : (
              <ChevronDown className="w-5 h-5 text-green-600" />
            )}
          </button>
          {(expandedSection === 'trends' || expandedSection === 'all') && (
            <div className="mt-2 p-4 bg-white rounded-lg border-2 border-green-100 space-y-3">
              {safeData.trends.map((trend, index) => (
                <div key={index} className="flex items-start gap-3 p-3 bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg border border-green-200">
                  <div className="flex-shrink-0 mt-1">
                    {trend.type === 'upward' ? (
                      <TrendingUp className="w-5 h-5 text-green-600" />
                    ) : (
                      <TrendingDown className="w-5 h-5 text-red-600" />
                    )}
                  </div>
                  <div className="flex-1">
                    <div className="font-semibold text-gray-900">{trend.metric}</div>
                    <div className="text-sm text-gray-700 mt-1">{trend.description}</div>
                    <div className="flex items-center gap-3 mt-2">
                      <span className={`text-sm font-bold ${trend.type === 'upward' ? 'text-green-600' : 'text-red-600'}`}>
                        {trend.change}
                      </span>
                      <span className="text-xs text-gray-500">
                        Confidence: {(trend.confidence * 100).toFixed(0)}%
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Anomalies */}
      {safeData.anomalies.length > 0 && (
        <div className="mb-4">
          <button
            onClick={() => toggleSection('anomalies')}
            className="w-full flex items-center justify-between p-4 bg-gradient-to-r from-orange-50 to-amber-50 rounded-lg border-2 border-orange-200 hover:border-orange-300 transition-colors"
          >
            <div className="flex items-center gap-3">
              <AlertTriangle className="w-6 h-6 text-orange-600" />
              <span className="text-lg font-bold text-orange-900">⚠️ Anomalies</span>
              <span className="px-2 py-1 bg-orange-200 text-orange-800 text-xs font-semibold rounded-full">
                {safeData.anomalies.length}
              </span>
            </div>
            {expandedSection === 'anomalies' ? (
              <ChevronUp className="w-5 h-5 text-orange-600" />
            ) : (
              <ChevronDown className="w-5 h-5 text-orange-600" />
            )}
          </button>
          {expandedSection === 'anomalies' && (
            <div className="mt-2 p-4 bg-white rounded-lg border-2 border-orange-100 space-y-3">
              {safeData.anomalies.map((anomaly, index) => (
                <div key={index} className={`p-3 rounded-lg border-2 ${getSeverityColor(anomaly.severity)}`}>
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="font-semibold">{anomaly.metric}</div>
                      <div className="text-sm mt-1">{anomaly.description}</div>
                      <div className="flex items-center gap-4 mt-2 text-sm">
                        <span>Expected: <strong>{anomaly.expected}</strong></span>
                        <span>Actual: <strong>{anomaly.actual}</strong></span>
                      </div>
                    </div>
                    <span className={`px-2 py-1 text-xs font-bold rounded uppercase ${
                      anomaly.severity === 'high' ? 'bg-red-200 text-red-800' :
                      anomaly.severity === 'medium' ? 'bg-orange-200 text-orange-800' :
                      'bg-yellow-200 text-yellow-800'
                    }`}>
                      {anomaly.severity}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Recommendations - HIDDEN per user request */}
      {false && safeData.recommendations.length > 0 && (
        <div className="mb-4">
          <button
            onClick={() => toggleSection('recommendations')}
            className="w-full flex items-center justify-between p-4 bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg border-2 border-purple-200 hover:border-purple-300 transition-colors"
          >
            <div className="flex items-center gap-3">
              <Target className="w-6 h-6 text-purple-600" />
              <span className="text-lg font-bold text-purple-900">🎯 Recommendations</span>
              <span className="px-2 py-1 bg-purple-200 text-purple-800 text-xs font-semibold rounded-full">
                {safeData.recommendations.length}
              </span>
            </div>
            {expandedSection === 'recommendations' ? (
              <ChevronUp className="w-5 h-5 text-purple-600" />
            ) : (
              <ChevronDown className="w-5 h-5 text-purple-600" />
            )}
          </button>
          {expandedSection === 'recommendations' && (
            <div className="mt-2 p-4 bg-white rounded-lg border-2 border-purple-100 space-y-3">
              {safeData.recommendations.map((rec, index) => (
                <div key={index} className="p-4 bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg border border-purple-200">
                  <div className="flex items-start gap-3">
                    <span className={`px-2 py-1 text-xs font-bold rounded uppercase border-2 ${getPriorityColor(rec.priority)}`}>
                      {rec.priority}
                    </span>
                    <div className="flex-1">
                      <div className="font-bold text-purple-900 text-base">{rec.action}</div>
                      <div className="text-sm text-gray-700 mt-2">
                        <strong>Why:</strong> {rec.reason}
                      </div>
                      <div className="text-sm text-gray-700 mt-1">
                        <strong>Impact:</strong> {rec.impact}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Summary - HIDDEN per user request */}
      {false && safeData.summary && (
        <div className="mt-6 p-5 bg-gradient-to-r from-gray-50 to-slate-50 rounded-lg border-2 border-gray-300 shadow-inner">
          <div className="flex items-start gap-3">
            <span className="text-3xl flex-shrink-0">📋</span>
            <div className="flex-1">
              <h4 className="font-bold text-gray-900 text-lg mb-2">Executive Summary</h4>
              <p className="text-gray-800 leading-relaxed">{safeData.summary}</p>
            </div>
          </div>
        </div>
      )}

      {/* Footer Info */}
      <div className="mt-4 text-center text-xs text-gray-500">
        <p>💡 AI-powered insights are generated from your dashboard data and may require human validation</p>
      </div>
    </div>
  );
};

export default AIInsightsChart;


